### PR TITLE
Created a file to convert Decimal to Binary in Java using while loops.

### PR DESCRIPTION
**Pull request by gupta-soham**

### CODE REVIEW

**Review by deepdalsania — COMMENTED** [review]
As per naming conventions, File name Should be in init cap.

**Review by deepdalsania — COMMENTED** [review]
kindly change name as per naming conventions. e.g DecToBin or Dec2Bin. 

Reference : https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by gupta-soham** [comment]
Updated, but why can't Camel Case work in this situation? I used to think that camel cases were the norm for Java file naming.

**Comment by gupta-soham** [comment]
@deepdalsania Please merge this PR if there aren't any issues.

**Comment by deepdalsania** [comment]
> Updated, but why can't Camel Case work in this situation? I used to think that camel cases were the norm for Java file naming.

I'm following init cap for java class file name so requesting you to change with that.

**Comment by deepdalsania** [comment]
> @deepdalsania Please merge this PR if there aren't any issues.

Class name would be in init cap but method name would be in camel case. More you can read about naming conventions from my shared link in previous comment.

**Comment by gupta-soham** [comment]
Updated and committed necessary changes

**Comment by gupta-soham** [comment]
Updated and committed necessary changes @deepdalsania

**Comment by gupta-soham** [comment]
is there any issue with this PR @deepdalsania

**Pull request closed without merging**
